#! /bin/sh
### BEGIN INIT INFO
# Provides:          chef-client-single
# Required-Start:    $local_fs $network
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: run chef-client once at boot
### END INIT INFO

PATH=/sbin:/bin

. /lib/lsb/init-functions

do_start () {
	log_action_msg "Running chef-client"
	exec /usr/bin/chef-client --once -l info
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
